# Сценарий для контролирования настраивания:
# * astra-audit-control
# * astra-audit-network-control
# * astra-bash-lock
# * astra-digsig-control
# 

---
- hosts: giss
  become: true
  tasks:
    - name: Проверка наличия файлов Astra
      stat:
        path: "/etc/audit/rules.d/{{ item }}"
      loop:
        - astra-syslog.rules
        - astra-syslog.rules.dpkg-dist
        - audit.rules
        - 10-parsec-nw.rules
        - 10-parsec.rules
      register: file_check_results

    - name: Создание словаря результатов
      set_fact:
        audit_files: {}

    - name: Заполнение словаря результатов
      set_fact:
        audit_files: "{{ audit_files | combine({item.item: (1 if item.stat.exists else 0)}) }}"
      loop: "{{ file_check_results.results }}"

    - name: Сохранение результатов в JSON-файл на удаленном хосте
      copy:
        content: "{{ audit_files | to_nice_json }}"
        dest: /tmp/audit_files.json

    - name: Получение JSON-файла на локальный хост
      fetch:
        src: /tmp/audit_files.json
        dest: /tmp/audit_files.json
        flat: yes

    - name: Вывод содержимого JSON-файла на локальном хосте
      debug:
        msg: "{{ lookup('file', '/tmp/audit_files.json') }}"
      delegate_to: localhost