# Сценарий для контролирования настраивания:
# + astra-audit-control
# + astra-audit-network-control
# * astra-bash-lock
# * astra-commands-lock
# * astra-digsig-control
# 

---
- hosts: giss
  become: true
  tasks:
    - name: Проверка наличия файлов Astra
      stat:
        path: "/etc/audit/rules.d/{{ item }}"
      loop:
        - astra-syslog.rules
        - astra-syslog.rules.dpkg-dist
        - audit.rules
        - 10-parsec-nw.rules
        - 10-parsec.rules
      register: file_check_results

    - name: Создание словаря результатов
      set_fact:
        audit_files: {}

    - name: Заполнение словаря результатов
      set_fact:
        audit_files: "{{ audit_files | combine({item.item: (1 if item.stat.exists else 0)}) }}"
      loop: "{{ file_check_results.results }}"

    - name: Проверка статуса astra-bash-lock
      command: astra-bash-lock status
      ignore_errors: yes
      register: bash_lock_status

    - name: Проверка статуса astra-commands-lock
      command: astra-commands-lock status
      ignore_errors: yes
      register: commands_lock_status

    - name: Проверка статуса astra-digsig-control
      command: astra-digsig-control status
      ignore_errors: yes
      register: digsig_control_status

    - name: Сохранение результатов в JSON-файл на удаленном хосте
      copy:
        content: |
          {
            "bash_lock": {{ '1' if bash_lock_status.stdout == 'АКТИВНО' else '0' }},
            "commands_lock": {{ '1' if commands_lock_status.stdout == 'АКТИВНО' else '0' }},
            "digsig_control": {{ '1' if digsig_control_status.stdout == 'АКТИВНО' else '0' }},
            
            "astra-syslog.rules": {{ audit_files['astra-syslog.rules'] }},
            "astra-syslog.rules.dpkg-dist": {{ audit_files['astra-syslog.rules.dpkg-dist'] }},
            "audit.rules": {{ audit_files['audit.rules'] }},
            "10-parsec-nw.rules": {{ audit_files['10-parsec-nw.rules'] }},
            "10-parsec.rules": {{ audit_files['10-parsec.rules'] }}
          }
        dest: /tmp/audit_control.json

    - name: Получение JSON-файла на локальный хост
      fetch:
        src: /tmp/audit_control.json
        dest: /tmp/audit_control.json
        flat: yes

    - name: Вывод содержимого JSON-файла на локальном хосте
      debug:
        msg: "{{ lookup('file', '/tmp/audit_control.json') }}"
      delegate_to: localhost