# Config file autologin:
# /etc/X11/fly-dm/fly-dmrc

- name: Parse and export autologin and other information
  hosts: giss
  become: yes
  tasks:

    - name: Read the /etc/X11/fly-dm/fly-dmrc file using grep
      shell:
        cmd: grep -E '^((AutoLoginEnable|AutoLoginAgain|AutoLoginDelay|AutoLoginUser))' /etc/X11/fly-dm/fly-dmrc
      register: fly_dmrc_output
      ignore_errors: yes

    - name: Debug fly_dmrc_output
      debug:
        var: fly_dmrc_output.stdout_lines

    - name: Parse fly-dmrc parameters
      set_fact:
        AutoLoginEnable: "{{ fly_dmrc_output.stdout_lines | select('match', '^AutoLoginEnable=') | map('regex_replace', '^AutoLoginEnable=(.*)', '\\1') | first | default('') }}"
        AutoLoginAgain: "{{ fly_dmrc_output.stdout_lines | select('match', '^AutoLoginAgain=') | map('regex_replace', '^AutoLoginAgain=(.*)', '\\1') | first | default('') }}"
        AutoLoginDelay: "{{ fly_dmrc_output.stdout_lines | select('match', '^AutoLoginDelay=') | map('regex_replace', '^AutoLoginDelay=(.*)', '\\1') | first | default('') }}"
        AutoLoginUser: "{{ fly_dmrc_output.stdout_lines | select('match', '^AutoLoginUser=') | map('regex_replace', '^AutoLoginUser=(.*)', '\\1') | first | default('') }}"

    - name: Initialize combined parameters
      set_fact:
        combined_params: []

    - name: Add AutoLog information to combined_params
      set_fact:
        combined_params: "{{ combined_params + [{'AutoLoginEnable': AutoLoginEnable, 'AutoLoginAgain': AutoLoginAgain, 'AutoLoginDelay': AutoLoginDelay, 'AutoLoginUser': AutoLoginUser}] }}"
      when:
        - AutoLoginEnable is defined
        - AutoLoginAgain is defined
        - AutoLoginDelay is defined
        - AutoLoginUser is defined

    - name: Debug parsed parameters
      debug:
        var: combined_params
      
    - name: Save AutoLogin information to JSON on remote machine
      copy: 
        content: "{{ combined_params | to_nice_json }}"
        dest: /tmp/AutoLogin.json
    
    - name: Fetch JSON file to local machine
      fetch:
        src: /tmp/AutoLogin.json
        dest: /tmp/AutoLogin.json
        flat: yes
      
    - name: Debug parsed parameters from file
      debug:
        msg: "{{ lookup('file', '/tmp/AutoLogin.json') }}"
      delegate_to: localhost
