- name: Parse and export pam.d common-password information
  hosts: giss
  become: yes
  tasks:

    - name: Read the /etc/pam.d/common-password file
      slurp:
        src: /etc/pam.d/common-password
      register: common_password_content

    - name: Parse the content of common-password
      set_fact:
        pam_parameters:
          retry: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*retry=([0-9-]+)') | first | default('') }}"
          difok: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*difok=([0-9-]+)') | first | default('') }}"
          minlen: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*minlen=([0-9-]+)') | first | default('') }}"
          lcredit: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*lcredit=([0-9-]+)') | first | default('') }}"
          ucredit: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*ucredit=([0-9-]+)') | first | default('') }}"
          dcredit: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*dcredit=([0-9-]+)') | first | default('') }}"
          ocredit: "{{ common_password_content.content | b64decode | regex_findall('pam_cracklib\\.so.*ocredit=([0-9-]+)') | first | default('') }}"

    - name: Initialize combined params
      set_fact:
        combined_params: []

    - name: Combine parsed parameters
      set_fact:
        combined_params: "[{{ pam_parameters }}]"

    - name: Debug parsed parameters
      debug:
        var: combined_params

    - name: Save pam.d information to JSON on remote machine
      copy:
        content: "{{ combined_params | to_nice_json }}"
        dest: /tmp/common_password.json

    - name: Fetch JSON file to local machine
      fetch:
        src: /tmp/common_password.json
        dest: /tmp/common_password.json
        flat: yes

    - name: Debug parsed parameters from file
      debug:
        msg: "{{ lookup('file', '/tmp/common_password.json') }}"
      delegate_to: localhost