---
- name: Установка и настройка NTP с основным сервером 192.168.1.92
  become: yes
  hosts: all
  tasks:
    - name: Настройка конфигурационного файла NTP
      lineinfile:
        path: /etc/ntp.conf
        regexp: '^server '
        line: 'server 192.168.1.92 iburst'
        state: present

    - name: Перезапуск службы NTP
      service:
        name: ntp
        state: restarted
        enabled: yes