- name: Parse and export pam.d common-auth information
  hosts: all
  become: yes
  tasks:

    - name: Read the /etc/pam.d/common-auth file
      slurp:
        src: /etc/pam.d/common-auth
      register: common_auth_content

    - name: Parse the content of common-auth
      set_fact:
        pam_parameters: "{{ common_auth_content.content | b64decode | regex_findall('pam_tally\\.so.*deny=([0-9]+)') | list }}"
        cracklib_params: "{{ common_auth_content.content | b64decode | regex_findall('pam_cracklib\\.so.*minlen=([0-9]+).*dcredit=([0-9]+).*ucredit=([0-9]+).*lcredit=([0-9]+).*') | list }}"

    - name: Combine parsed parameters
      set_fact:
        combined_params: []
      loop: "{{ cracklib_params }}"
      loop_control:
        index_var: index
      set_fact:
        combined_params: "{{ combined_params + [{'minlen': item.0, 'dcredit': item.1, 'ucredit': item.2, 'lcredit': item.3}] }}"

    - name: Add deny parameter to combined params
      set_fact:
        combined_params: "{{ [{'deny': pam_parameters[0]}] + combined_params }}"

    - name: Debug parsed parameters
      debug:
        var: combined_params

    - name: Save pam.d information to JSON on remote machine
      copy:
        content: "{{ combined_params | to_nice_json }}"
        dest: /tmp/sys_info.json

    - name: Fetch JSON file to local machine
      fetch:
        src: /tmp/sys_info.json
        dest: /tmp/sys_info.json
        flat: yes

    - name: Debug parsed parameters from file
      debug:
        msg: "{{ lookup('file', '/tmp/sys_info.json') }}"
      delegate_to: localhost