---
- name: Get login.defs parameters
  hosts: all
  gather_facts: no
  tasks:
    - name: Read login.defs file
      slurp:
        src: /etc/login.defs
      register: login_defs_raw

    - name: Parse login.defs content
      set_fact:
        login_defs_info: >-
          {{
            login_defs_raw.content | b64decode | regex_findall('\\w+:\\s*\\S+') | map('regex_replace', '^(\\w+):\\s*(\\S+)', '\\1:\\2') | map('split', ':') | items2dict
          }}

    - name: Ensure the output directory exists
      file:
        path: /tmp
        state: directory

    - name: Write the login_defs info to JSON file
      copy:
        dest: /tmp/sys_info.json
        content: |
          {
            "login_defs": {{ login_defs_info | to_json }}
          }

    - name: Display found parameters
      debug:
        msg: "{{ login_defs_info }}"
