---
- name: Parse and export pam.d common-auth information
  hosts: all
  become: yes
  tasks:

    - name: Read the /etc/pam.d/common-auth file
      slurp:
        src: /etc/pam.d/common-auth
      register: common_auth_content

    - name: Parse the content of common-auth
      set_fact:
        pam_parameters: |
          {% set pam_tally_deny = None %}
          {% set cracklib_params = [] %}
          {% for line in common_auth_content.content | b64decode | splitlines %}
            {% set line = line.strip() %}
            {% if not line or line.startswith('#') %}
              {% continue %}
            {% endif %}
            
            {% set parts = line.split() %}
            
            {% if 'pam_tally.so' in parts %}
              {% for part in parts %}
                {% if part.startswith('deny=') %}
                  {% set pam_tally_deny = part.split('=')[1] %}
                {% endif %}
              {% endfor %}
            {% endif %}

            {% if 'pam_cracklib' in parts %}
              {% set params = parts[3:] %}
              {% set param_dict = {} %}
              {% for param in params %}
                {% if '=' in param %}
                  {% set key_value = param.split('=') %}
                  {% set _ = param_dict.update({key_value[0]: key_value[1]}) %}
                {% endif %}
              {% endfor %}
              {% set _ = cracklib_params.append(param_dict) %}
            {% endif %}
          {% endfor %}

          {% if pam_tally_deny is not none %}
            {% set _ = cracklib_params.append({'deny': pam_tally_deny}) %}
          {% endif %}

          {{ cracklib_params }}

    - name: Print parsed parameters
      debug:
        var: pam_parameters

    - name: Save pam.d information to JSON on remote machine
      copy:
        content: "{{ pam_parameters | to_nice_json }}"
        dest: /tmp/sys_info.json

    - name: Fetch JSON file to local machine
      fetch:
        src: /tmp/sys_info.json
        dest: /tmp/sys_info.json
        flat: yes