---
- name: Install and configure Zabbix agent
  hosts: giss
  become: yes  # Используем привилегии root
  vars:
    zabbix_active_server: "192.168.111.232"  # IP активного сервера
    zabbix_passive_server: "192.168.111.232" # IP пассивного сервера
    zabbix_metadata: "GIS"      # Метаданные агента
    zabbix_EnableRemoteCommands: "1"
    zabbix_LogRemoteCommands: "1"

  tasks:
    - name: Install Zabbix agent
      apt: 
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent (set passive server)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_passive_server }}"
        create: yes

    - name: Configure Zabbix agent (set active server)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_active_server }}"
        create: yes

    - name: Configure Zabbix agent (set hostname)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ inventory_hostname }}"
        create: yes

    - name: Configure Zabbix agent (set metadata)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^HostMetadata='
        line: "HostMetadata={{ zabbix_metadata }}"
        create: yes

    - name: Configure Zabbix agent (set EnRemCtrl)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^EnableRemoteCommands='
        line: "EnableRemoteCommands={{ zabbix_EnableRemoteCommands }}"
        create: yes
    
    - name: Configure Zabbix agent (set LogRemCtrl)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^LogRemoteCommands='
        line: "LogRemoteCommands={{ zabbix_LogRemoteCommands }}"
        create: yes

    - name: Restart Zabbix agent service
      systemd:  # Используем модуль systemd для управления сервисом
        name: zabbix-agent
        state: restarted
        enabled: yes